{
 "title": "Fermentation",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Approximate Gravity",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "fermgravity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fermentation Temperature (Measured From Thermowell)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ferm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fermentation Chamber",
   "type": "graph",
   "description": "0 = heating and cooling off\n1 = heating on and cooling off\n-1 = heating off and cooling on",
   "gridPos": { "h": 4, "w": 16, "x": 7, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fermchamber",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}