#!/bin/bash

#rm -fr .cache
mkdir -p .cache


# Usage: ./compile "brewerslab integrationtest"


echo "Creating YIN files...."
cd yang
for file in *.yang
do
  yin=`echo $file | sed -e 's/.yang//'`
  echo "   $file"
  pyang -f yin $file >../.cache/$yin.yin
  pyang -f tree $file >../.cache/$yin.txt
  yanglist="$yin $yanglist"
done

echo "Converting to CRUX files...."
cd ../
ls .cache/*

if [ "$1" = "" ]
then
  yangmodules=$yanglist
else
  yangmodules=$1
fi

PYTHONPATH="blng:$PYTHONPATH" python blng/Yang.py $yangmodules


echo "Combining into single document"
xmllint --format .cache/__crux-schema.xml >crux-example.xml
echo "  OK"
