#!/bin/bash

# Usage: ./compile "brewerslab integrationtest"

one=$1
NEW_PYTHON_PATH="blng:$PYTHONPATH"


yanglist=""
timeyangchanged=`stat -f %m yang`
timelastcompiled=`stat -f %m crux-example.xml`
if [ $timelastcompiled -gt $timeyangchanged ]
then
	if [ -d .cache ]
	then
		echo "No changes in the yang - skipping compile"
		exit 0
	fi
fi

#rm -fr .cache
mkdir -p .cache

set -euo pipefail
IFS=$'\n\t'


echo "Creating YIN files...."
cd yang
for file in *.yang
do
  yin=`echo $file | sed -e 's/.yang$//'`

  timeyangchanged=`stat -f %m $file`
  if [ -f ../.cache/$yin.yin ]
  then
    timelastcompiled=`stat -f %m ../.cache/$yin.yin`
  else
    timelastcompiled=0
  fi
  if [ $timelastcompiled -gt $timeyangchanged ]
  then
    echo " ($file) using cached version"
  else
    echo "   $file"
    pyang -f yin $file >../.cache/$yin.yin
    pyang -f tree $file >$yin.txt
  fi
  yanglist="$yin $yanglist"
done

echo "Converting to CRUX files...."
cd ../

if [ "$one" = "" ]
then
  yangmodules=$yanglist
else
  yangmodules=$1
fi

timeyangchanged=`stat -f %m .cache`
timelastcompiled=`stat -f %m crux-example.xml`
if [ $timelastcompiled -lt $timeyangchanged ]
then
  PYTHONPATH=$NEW_PYTHON_PATH python blng/Yang.py $yangmodules

  echo "Combining into single document"
  xmllint --format .cache/__crux-schema.xml >crux-example.xml
else
  echo "  Using cached version"
fi
echo "  OK"
