#!/usr/bin/env python3

import argparse
import os
import imp
import sys
import importlib

description = """
Launch a PyConfHoard 'thing'.
"""
parser = argparse.ArgumentParser(description=description)
parser.add_argument('--thing', help="Path to a thing (e.g. things/temperature/TemperatureProviderDS18B20.py)")
parser.add_argument('--rest', action='store_true')
parser.add_argument('--cli', action='store_true')
parser.add_argument('--debug', action='store_true', help="Launch in interactive debug mode")
parser.add_argument('--register', action='store_true', help="Register the yang module")
args = parser.parse_args()


if not args.thing and not args.rest and not args.cli:
    sys.stderr.write('Either --thing or --rest or --cli required')
    sys.exit(1)

if args.rest:
    os.system('gunicorn --reload pyconfhoard.rest.server')
elif args.cli:
    os.chdir('pyconfhoard/cli')
    os.system('PYTHONPATH=$PYTHONPATH:../ python cli.py')
elif os.path.exists(args.thing):
    path = args.thing.split('/')
    os.chdir('things')
    if os.path.exists('%s/%s' % (path[1], path[2])):
        os.chdir(path[1])
        sys.path.insert(0, '../../pyconfhoard')
        sys.path.insert(0, '../../yang')
        py_mod = imp.load_source(path[2].split('.')[0], path[2])
        launcher = getattr(py_mod, 'Launch')
        if args.debug:
            import IPython
            print('Running from %s' % (os.getcwd()))
            launch = launcher
            IPython.embed(display_banner=False)
        elif args.register:
            launch = launcher()
            launch.thing.register()
        else:
            launch = launcher()
            launch.thing.start()

    else:
        raise ValueError('%s not a valid thing - cannot launch' % (args.thing))

else:
    raise ValueError('%s does not exist' % (args.thing))
